config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope  :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root  'tweets#index'
  resources :users, only: [:show]
  resources :tweets
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  mount_uploader  :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many  :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :weight])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # binding.pry
  before_action :move_to_index, except: :index

  def index
    @tweets = Tweet.order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweet_params)
    redirect_to action: :index
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params) if @tweet.user_id == current_user.id
    redirect_to action: :index
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy if tweet.user_id == current_user.id
    redirect_to action: :index
  end

  private

  def tweet_params
    minutes = params.require(:tweet).permit(:minutes)[:minutes].to_i
    weight = current_user.weight
    params.require(:tweet).permit(:text, :image, :minutes).merge(user_id: current_user.id, calorie: calculate_calorie(weight, minutes))
  end

  def calculate_calorie(weight, minutes)
    calorie = (3 * weight * minutes / 60 * 1.05).floor(0)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>お写ん歩Walking</title>
  <style type="text.css" href="./style.css"></style>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
</head>
<body>
  <nav>
    <div class="nav-wrapper #64ffda teal accent-2">
      <%= link_to "お写ん歩 Walking" , root_path, class: "brand-logo center" %>
        <% if user_signed_in? %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
              <%= link_to "マイページ", "#" %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> 
            </li>
            <li>
              <%= link_to "投稿する", new_tweet_path, method: :get %>
            </li>
          </ul>
        <% else %>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li>
              <%= link_to "ログイン", new_user_session_path, method: :get %>
            </li>
            <li>
              <%= link_to "新規登録", new_user_registration_path, method: :get %>
            </li>
          </ul>

        <% end %>
    </div>
  </nav>
   <%= yield %>
</body>
</html>

app/views/tweets/_tweet.html.erb
<div class="row">
  <div class="col s6 offset-s3">
    <div class="card">
      <div class="card-image">
        <%= image_tag tweet.image.url if tweet.image.present? %>
      </div>
      <div class="card-content">
        <%= simple_format(tweet.text) %><br>
        <p>歩いた日：<%= tweet.created_at.strftime("%Y/%m/%d %H:%M") %></p>
        <p>消費カロリー：<%= tweet.calorie %>[kcal]</p>
      </div>
      <div class="card-action btns" id="fabs">
        <%= link_to "投稿者:#{tweet.user.name}", "/users/#{tweet.user_id}", class: "name" %>
        <% if user_signed_in? && current_user == tweet.user %>
          <ul>
            <li>
              <%= link_to '編集', edit_tweet_path(tweet.id), method: :get, class: 'btn', id: 'fab' %>
            </li>
            <li>
              <%= button_to '削除', "/tweets/#{tweet.id}", method: :delete, class: 'btn', id: 'fab' %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

<style>
#fabs li {
  display: inline-block;
  list-style: none;
  float: right;
  margin-right: 5px;
}

#fabs {
  height: 90px;
}

.name {
  display: inline;
  float: left;
  line-height: 57px;
}
</style>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <%= form_for(@tweet) do |f| %>
      <h3>
        編集する
      </h3>
      <%= f.text_field :text, placeholder: "お散歩メモ" %>
      <%= f.file_field :image, placeholder: "画像ファイル選択" %>
      <%= f.number_field :minutes, placeholder: "何分歩いたかな?" %>
        <%= button_tag type: "submit" do %>
          投稿する
        <% end %>
    <% end %>
  </div>
</div>

app/views/tweets/index.html.erb
<%# <div class="center"><h3>お散歩日記</h3></div> %>
<br><br>
  <script type="text/javascript" src="./app.js"></script>
    <% @tweets.each do |tweet| %>
      <%= render partial: "tweet", locals:{tweet: tweet} %>
    <% end %>
  <%= paginate(@tweets) %>
  

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_for(@tweet) do |f| %>
      <h3>
        投稿する
      </h3>
      <%= f.text_field :text, placeholder: "お散歩メモ" %>
      <%= f.text_field :image, placeholder: "画像Url" %>
      <%= f.number_field :steps, placeholder: "何歩歩いたかな?" %>
        <%= button_tag type: "submit" do %>
          投稿する
        <% end %>
    <% end %>
  </div>
</div>